### ISSUE TITLE
Clicking on the "View menu"-link didn't work any more after update to 3.0.4

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#17]
**Expected behavior:**
Clicking on the "View menu"-link in the top-navigation the menu should be shown.

**Actual behavior:**
Clicking on the "View menu"-link in the top-navigation a blank page with the text "Something went wrong and the page cannot be displayed"

**Reproduce steps:**
- Call the main page of your TI (active theme is the Orange Theme)
- Click in the top-navigation on the link "View menu"

Thats all. Now you should see the blank page with the text  "Something went wrong and the page cannot be displayed"

**Version:**
TastyIgniter version number: 3.0.4

**Additional Information:**
I updated the TatsyIgniter to the new version and after that the link didn't work any more.

In the system-logs I found the following information:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function lt() on null
in /httpdocs/vendor/tastyigniter/flame/src/Location/WorkingSchedule.php:462
Stack trace:
#0 /httpdocs/vendor/tastyigniter/flame/src/Location/WorkingSchedule.php(327): Igniter\Flame\Location\WorkingSchedule->createPeriodForDays(Object(Carbon\Carbon))
#1 /httpdocs/extensions/igniter/local/classes/Location.php(281): Igniter\Flame\Location\WorkingSchedule->getTimeslot(Object(DateInterval), Object(Carbon\Carbon), 15)
#2 /httpdocs/extensions/igniter/local/components/LocalBox.php(195): Igniter\Local\Classes\Location->scheduleTimeslot()
#3 /httpdocs/extensions/igniter/local/components/LocalBox.php(109): Igniter\Local\Components\LocalBox->prepareVars()
#4 /httpdocs/app/main/template/concerns/HasComponents.php(102): Igniter\Local\Components\LocalBox->onRun()
#5 /httpdocs/app/main/classes/MainController.php(301): Main\Template\Model->runComponents()
#6 /httpdocs/app/main/classes/MainController.php(260): Main\Classes\MainController->execPageCycle()
#7 /httpdocs/app/main/classes/MainController.php(196): Main\Classes\MainController->runPage(Object(Main\Template\Page))
#8 /httpdocs/app/system/classes/Controller.php(85): Main\Classes\MainController->remap('mk/menus')
#9 /httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): System\Classes\Controller->run('mk/menus')
#10 /httpdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#11 /httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(System\Classes\Controller), 'run')
#12 /httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#13 /httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#14 /httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /httpdocs/vendor/tastyigniter/flame/src/Currency/Middleware/CurrencyMiddleware.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Currency\Middleware\CurrencyMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /httpdocs/extensions/igniter/cart/middleware/CartMiddleware.php(12): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Cart\Middleware\CartMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /httpdocs/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Translation\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /httpdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
```

**Comment by git-gnulf** [comment]
I 've some new information. I find out that the scheddule-plan for a location is the reason for that error. 

In my case we dont deliver to our guests so I've no delivery plan:
![2021-06-28_22-15](https://user-images.githubusercontent.com/85353101/123699171-3d7c9680-d85f-11eb-88c7-1da16f232ac0.png)

If I edit this option and add only one timeslot for delivery, so I'm surprised all works fine:
![2021-06-28_22-24](https://user-images.githubusercontent.com/85353101/123699500-a5cb7800-d85f-11eb-9eec-bd2bc6c198d4.png)
Now I can call the View-Menu-Link and I see all my products. So far so good.

But this delivery-scheddule is wrong for us, so I want to reset this delivery-plan. If I remove the one time-slot I set for testing, I cant save this dialog:
![2021-06-28_22-14_2](https://user-images.githubusercontent.com/85353101/123699720-e0cdab80-d85f-11eb-87e5-ad1c0b9f1e63.png)

Hope it helps

**Comment by ryanmitchell** [comment]
I fixed the lt() issue yesterday and it will be in the next release.
But if youre not offering delivery this is the wrong approach - just deselect "Offers delivery" on the location settings.

**Comment by git-gnulf** [comment]
> I fixed the lt() issue yesterday and it will be in the next release.
Perfect. Thank you! :)

> But if youre not offering delivery this is the wrong approach - just deselect "Offers delivery" on the location settings.
Yes, of course, I agree. That was my original approach. 
But searching for a solution I played with all the options and recognized, that if I chose a time for delivery, the link works. The "Offers delivery" on the location settings was still deselected. And the timeslot for delivery was a stupid setup of 2 minutes ;)

**Comment by git-gnulf** [comment]
I think we can close this issue ;) 
In version 3.0.5 this error is fixed.
